In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('customer.csv')

In [22]:
df.sample(5)

age  gender review education purchased
23   96  Female   Good    School        No
18   19    Male   Good    School        No
46   64  Female   Poor        PG        No
14   15    Male   Poor        PG       Yes
38   45  Female   Good    School        No

In [23]:
df = df.iloc[:,2:]

In [24]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],
                                                    df.iloc[:,-1],
                                                    test_size=0.2,
                                                   )

X_train.shape, X_test.shape

((40, 2), (10, 2))

In [27]:
X_train

review education
4   Average        UG
43     Poor        PG
12     Poor    School
22     Poor        PG
37  Average        PG
7      Poor    School
40     Good    School
30  Average        UG
9      Good        UG
46     Poor        PG
36     Good        UG
23     Good    School
1      Poor        UG
29  Average        UG
2      Good        PG
24  Average        PG
5   Average    School
16     Poor        UG
32  Average        UG
41     Good        PG
33     Good        PG
18     Good    School
25     Good    School
31     Poor    School
8   Average        UG
28     Poor    School
6      Good    School
42     Good        PG
17     Poor        UG
21  Average        PG
47     Good        PG
10     Good        UG
49     Good        UG
19     Poor        PG
27     Poor        PG
44  Average        UG
11     Good        UG
0   Average    School
3      Good        PG
45     Poor        PG

In [28]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [29]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [30]:
X_train = oe.transform(X_train)
X_test = oe.transform( X_test)

In [31]:
X_train

array([[1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.]])

In [32]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [33]:
X_test

array([[0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.]])

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
le = LabelEncoder()

In [36]:
le.fit(y_train)

LabelEncoder()

In [37]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [38]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [39]:
y_train


array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1])